
imageFileNames = {'E:\专业必修\电综\单目测距\photo_biaoding\1.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\2.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\3.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\4.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\5.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\6.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\9.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\10.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\11.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\12.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\13.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\14.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\15.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\16.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\17.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\18.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\19.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\20.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\21.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\22.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\23.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\24.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\25.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\26.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\27.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\28.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\29.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\30.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\31.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\32.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\33.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\34.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\35.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\36.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\37.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\38.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\39.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\40.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\41.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\42.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\43.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\44.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\45.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\46.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\47.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\48.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\49.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\50.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\51.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\52.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\53.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\54.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\55.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\56.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\57.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\58.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\59.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\60.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\61.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\62.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\63.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\79.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\80.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\81.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\82.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\83.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\84.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\85.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\86.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\87.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\88.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\89.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\90.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\91.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\92.jpg',...
    'E:\专业必修\电综\单目测距\photo_biaoding\93.jpg',...
    };

[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);


squareSize = 25;  
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', true, 'EstimateTangentialDistortion', true, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

h1=figure; showReprojectionErrors(cameraParams);

h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

displayErrors(estimationErrors, cameraParams);

undistortedImage = undistortImage(originalImage, cameraParams);

